---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
  namespace: ${NAMESPACE}
  labels:
    app: ${APP_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APP_NAME}
  strategy:
    type: Recreate
  template:
    metadata:
      name: ${APP_NAME}
      labels:
        app: ${APP_NAME}
    spec:
      containers:
      - name: ${APP_NAME}
        imagePullPolicy: Always
        image: ${IMAGE_NAME}
        ports:
        - containerPort: 1330
          name: ${APP_NAME}
      restartPolicy: Always
